apiVersion: v1
kind: Secret
metadata:
  name: pqrs-postgres-secret
  namespace: pqrs-saas
type: Opaque
stringData:
  POSTGRES_DB: pqrs_saas_db
  POSTGRES_USER: pqrs_user
  POSTGRES_PASSWORD: PqrsSecurePassword123!
