apiVersion: v1
kind: Service
metadata:
  name: pqrs-postgres-service
  namespace: pqrs-saas
  labels:
    app: pqrs-postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
  selector:
    app: pqrs-postgres
