apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pqrs-ingress
  namespace: pqrs-saas
spec:
  rules:
    - host: camilo-pqrs.paxos.jaramc.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pqrs-api-service
                port:
                  number: 80
